import { Geist, Geist_Mono } from "next/font/google";
import { ToastContainer } from "react-toastify";
import SessionProvider from "next-auth/react"
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ Component, children, pageProps: { session, ...pageProps} }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastContainer />
       <SessionProvider session={session}>
          <Component {...pageProps}/>
          {children}
        </SessionProvider> 
      </body>
    </html>
  );
}
